about/urls.py
from django.urls import path
from . import views

app_name = 'about'


urlpatterns =[
    path('', views.aboutme, name= 'about'),
    path('<slug>', views.about_details, name='detail'),
    ]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('<slug>', views.blog_details, name='detail'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'
urlpatterns = [
    path('', views.contact, name = 'contact')
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns =[
    path('', views.home, name='home')
]

#import unittest


#class MyTestCase(unittest.TestCase):
#   def test_something(self):
  #      self.assertEqual(True, False)


#if __name__ == '__main__':
#    unittest.main()

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('home.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('photo/', include('photo.urls')),
    path('blog', include('blog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from . import views

app_name = 'photo'

urlpatterns =[
    path('', views.photo, name='album')
]

about/models.py
from django.db import models
from django.contrib.auth.models import User


class About(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)


    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Blog(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)


    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

contact/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

photo/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render
from .models import About


def aboutme(request):
    about = About.objects.all().order_by('date')
    return render(request, 'mysite_about.html', {'about': about})


def about_details(request, slug):
    article= About.objects.get(slug=slug)
    return render(request, 'mysite_about_article.html', {'article': article})

blog/views.py
from django.shortcuts import render
from .models import Blog


def blog(request):
    blog = Blog.objects.all().order_by('date')
    return render(request, 'mysite_blog.html', {'blog': blog})


def blog_details(request, slug):
    article= Blog.objects.get(slug=slug)
    return render(request, 'mysite_blog_article.html', {'article': article})

contact/views.py
from django.shortcuts import render


def contact(request):
    return render(request, 'mysite_contact.html')

home/views.py
from django.shortcuts import render



def home(request):
    return render(request, 'mysite_home.html')

photo/views.py
from django.shortcuts import render



def photo(request):
    return render(request, 'mysite_photos.html')

templates/mysite_about.html
{% extends 'mysite_base.html' %}
{% block content %}
<h1>Articles list</h1>
<div class="about">
    {% for about in about %}
        <div class="article">
              <h2><a href="{% url 'about:detail' slug=about.slug %}">{{ about.title }}</a></h2>
            <p class="snippet">{{ about.snippet }}</p>
            <p class="date">{{ about.date }}</p>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/mysite_about_article.html
{% extends 'mysite_base.html' %}
{% block content %}

<div class="article_list">
        <div class="article_details">
            <img src="{{ article.thumb.url }}" />

            <h2>{{ article.title }}</h2>
            <h5>{{ article.body }}</h5>
            <h3>{{ article.date }}</h3>

        </div>
</div>
{% endblock %}

templates/mysite_base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Said</title>
     <link rel="stylesheet" href="{%static 'styles.css'%}">
    <h1 href="{%url 'home:home'%}"><img src="{%static 'ball2.png'%}" alt="">Said's personal website...</h1>

    <nav>
    <ul>
        <li>
            <a href="{% url 'home:home' %}" class="button">Home </a>
        </li>
        <li>
        <a href="{% url 'about:about' %}" class="button">About me</a>
        </li>
        <li>
            <a href="{% url 'contact:contact' %}" class="button">Contact</a>
        </li>
        <li>
            <a href="{% url 'photo:album' %}" class="button">Photos</a>
             {% csrf_token%}
        </li>
        <li>
             <a href="{% url 'blog:blog' %}" class="button">Blog</a>
        </li>
    </ul>
</head>
<body>
<div class="wrapper">
    {%block content%}
    {%endblock%}
</div>
</body>
</html>

templates/mysite_blog.html
{% extends 'mysite_base.html' %}
{% block content %}
<h1>Articles list</h1>
<div class="about">
    {% for blog in blog %}
        <div class="article">
              <h2><a href="{% url 'blog:detail' slug=blog.slug %}">{{ blog.title }}</a></h2>
            <p class="snippet">{{ blog.snippet }}</p>
            <p class="date">{{ blog.date }}</p>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/mysite_blog_article.html
{% extends 'mysite_base.html' %}
{% block content %}
{% load static from staticfiles %}

<div class="article_list">
        <div class="article_details">
            <img src="{{ article.thumb.url }}" />
            <h2>{{ article.title }}</h2>
            <h5>{{ article.body }}</h5>
            <h3>{{ article.date }}</h3>
            <p>{{ article.author.username }}</p>

        </div>
</div>
{% endblock %}

templates/mysite_contact.html
{% extends 'mysite_base.html' %}
{% block content %}
<body>
<div class="contact">
     <nav>
    <ul>
         <li><h2><a href="https://www.facebook.com/chem.sa3id/">Facebook</a></h2></li>
        <li>
            <h2><a href="https://www.linkedin.com/in/elsaid-mohamed-39974495/">Linkedin</a></h2>
        </li>



    </ul>
 </nav>
    <div class="email">
       <h1> You can contact me at elkhot@gmail.com<a href="mailto:elkhot@gmail.com">Click here to send</a></h1>
    </div>

    <div class="mobile">
        <h1>My cell phone is 00201026680536<a>available on WhatsApp and on Telegram</a></h1>
    </div>
</div>
</body>
</html>
{% endblock %}

templates/mysite_home.html
{% extends 'mysite_base.html' %}
{% block content %}
{% load static from staticfiles %}



<div class="Main">
    <h2>Elsid Younes >>></h2>
        <p>Hold a master degree in chemistry.
            I have a neuro-muscular disease called Friedreich's ataxia disease (fA).
            Therefore, I am on a wheelchair since 2010.</p>

    <div class="ask">
        <h2>Hi guys and welcome to my personal website,,,,

        Let's do something together to change the world!</h2>
    </div>

</div>

{% endblock %}

templates/mysite_photos.html
{% extends 'mysite_base.html' %}
{% block content %}
{% load static from staticfiles %}


        <div class="photo">
            <a href="{%static '1.jpg'%}">
<img src="{% static '1.jpg' %}" width="300px" height="250px">Egypt 1983
</a>
                    <a href="{%static '2.jpg'%}">
<img src="{% static '2.jpg' %}" width="300px" height="250px">Egypt 1994
</a>
            <a href="{%static '8.jpg'%}">
<img src="{% static '8.jpg' %}" width="300px" height="250px">Egypt 2005
</a>        <a href="{%static '5.jpg'%}">
<img src="{% static '5.jpg' %}" width="300px" height="250px">Egypt 2008
</a>        <a href="{%static '4.jpg'%}">
<img src="{% static '4.jpg' %}" width="300px" height="250px"Sweden 2011
</a>        <a href="{%static '7.jpg'%}">
<img src="{% static '7.jpg' %}" width="300px" height="250px">Spain 2012
</a>        <a href="{%static '3.jpg'%}">
<img src="{% static '3.jpg' %}" width="250px" height="250px">Sweden 2013
</a>
        </div>


{% endblock %}